export const SystemOnlyDispatches: string[] = [];

export const KnownSystemDispatchers: string[] = [
  "fs-mount-drive",
  "fs-umount-drive",
  "fs-flush-folder",
  "fs-flush-file",
  "update-notifications",
  "send-notification",
  "delete-notification",
  "ragui-loggedin",
  "app-store-refresh",
  "stack-busy",
  "stack-not-busy",
  "ip-confirm",
  "ip-cancel",
  "elevation-approve",
  "elevation-deny",
  "window-unfullscreen",
  "window-closing",
  "window-unmaximize",
  "window-minimize",
  "window-maximize",
  "window-unminimize",
  "window-fullscreen",
  "totp-unlock-success",
  "totp-unlock-cancel",
  "pfp-changed",
  "mugui-done",
  "ls-confirm",
  "ls-cancel",
];
