import { svelte } from "@sveltejs/vite-plugin-svelte";
import { defineConfig, Plugin } from "vite";
import path, { resolve } from "path";
import ts from "typescript";
import { writeFile } from "fs/promises";

// https://vite.dev/config/
export default defineConfig({
  plugins: [svelte(), GenerateGlobalTypesPlugin()],
  envPrefix: "DW_",
  resolve: {
    alias: {
      $assets: resolve(__dirname, "./src/assets"),
      $state: resolve(__dirname, "./src/state"),
      $apps: resolve(__dirname, "./src/apps"),
      $css: resolve(__dirname, "./src/css"),
      $types: resolve(__dirname, "./src/types"),
      $ts: resolve(__dirname, "./src/ts"),
      $lib: resolve(__dirname, "./src/lib"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.includes("node_modules")) return "vendor";
        },
      },
    },
    assetsInlineLimit: 1,
    minify: false,
  },
  base: "",
});
function GenerateGlobalTypesPlugin(): Plugin {
  return {
    name: "generate-global-types",
    apply: "build",
    async buildStart() {
      const thirdPartyPath = path.resolve(__dirname, "src/ts/server/user/thirdparty.ts");

      // Load and parse the source file
      const program = ts.createProgram([thirdPartyPath], {
        allowJs: false,
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ESNext,
        moduleResolution: ts.ModuleResolutionKind.NodeJs,
        noEmit: true,
      });

      const checker = program.getTypeChecker();
      const source = program.getSourceFile(thirdPartyPath);
      if (!source) return;

      const typeAlias = [...source.statements].find(
        (stmt): stmt is ts.TypeAliasDeclaration => ts.isTypeAliasDeclaration(stmt) && stmt.name.text === "ThirdPartyPropMap"
      );
      if (!typeAlias) return;

      const type = checker.getTypeAtLocation(typeAlias);

      const props = type.getProperties().map((symbol) => {
        const name = symbol.getName();
        return `declare const ${name}: ThirdPartyPropMap["${name}"];`;
      });

      const content = `// AUTO-GENERATED BY VITE PLUGIN\nimport type { ThirdPartyPropMap } from "./ts/server/user/thirdparty";\n\n${props.join(
        "\n"
      )}\n\nexport {};`;

      await writeFile(path.resolve(__dirname, "dist/globals.d.ts"), content);
    },
  };
}
