name: Manual bug report PBI
description: File a bug report PBI
title: "As a user "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the bug report with all required details. Keep the format consistent.

  - type: textarea
    id: callstack
    attributes:
      label: Callstack
      description: Paste the full error callstack from the console or logs.
      render: shell
    validations:
      required: true

  - type: textarea
    id: affected-code
    attributes:
      label: Affected code
      description: Paste the minimal code snippet where the bug occurs.
      render: javascript
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Define the conditions that must be met for this issue to be resolved.
    validations:
      required: true
