import type { ThemeStore } from "$types/theme";

export const BuiltinThemes: ThemeStore = {
  wilhelminaSunset: {
    author: "SWHFotografie",
    version: "1.0",
    name: "Wilhelmina Sunset",
    taskbarLabels: false,
    taskbarDocked: true,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img18",
    desktopTheme: "dark",
    desktopAccent: "FF6842",
    loginBackground: "img18",
  },
  snowyMountains: {
    author: "Allucat1000",
    version: "1.0",
    name: "Snowy Mountains",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img33",
    desktopTheme: "light",
    desktopAccent: "66D9FF",
    loginBackground: "img33",
  },
  germanicWaterfall: {
    author: "Allucat1000",
    version: "1.0",
    name: "Germanic Waterfall",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img34",
    desktopTheme: "light",
    desktopAccent: "FFCB3D",
    loginBackground: "img34",
  },
  snowyWandelbos: {
    author: "SWHFotografie",
    version: "1.0",
    name: "Snowy Wandelbos",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img08",
    desktopTheme: "dark",
    desktopAccent: "94DBFF",
    loginBackground: "img08",
  },
  mykonosSeaside: {
    author: "Kees van Voorthuizen",
    version: "1.0",
    name: "Mykonos Seaside",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img01",
    desktopTheme: "light",
    desktopAccent: "00AAFF",
    loginBackground: "img01",
  },
  eveningLakeside: {
    author: "Saw Ramsson",
    version: "1.0",
    name: "Evening Lakeside",
    taskbarLabels: false,
    taskbarDocked: true,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img22",
    desktopTheme: "dark",
    desktopAccent: "6DA0D0",
    loginBackground: "img22",
  },
  sunsetInMykonos: {
    author: "Kees van Voorthuizen",
    version: "1.0",
    name: "Sunset in Mykonos",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: false,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img02",
    desktopTheme: "light",
    desktopAccent: "CEBA3B",
    loginBackground: "img02",
  },
  evningNeighbourhood: {
    author: "Matteo Scaringi",
    version: "1.0",
    name: "Evening Neighbourhood",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img27",
    desktopTheme: "dark",
    desktopAccent: "FFA200",
    loginBackground: "img27",
  },
  redBridgeLake: {
    author: "Saw Ramsson",
    version: "1.0",
    name: "Red Bridge Lake",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: true,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img23",
    desktopTheme: "light",
    desktopAccent: "FF7575",
    loginBackground: "img23",
  },
  hagueNightfall: {
    author: "SWHFotografie",
    version: "1.0",
    name: "Hague Nightfall",
    taskbarLabels: false,
    taskbarDocked: false,
    taskbarColored: true,
    noAnimations: false,
    sharpCorners: false,
    compactContext: false,
    noGlass: false,
    desktopWallpaper: "img13",
    desktopTheme: "dark",
    desktopAccent: "FFB35C",
    loginBackground: "img13",
  },
};

export const VisualStyles: Record<string, string> = {
  dark: "Dark",
  light: "Light",
};
