export const AdminScopes = {
  adminGod: "admin.god",
  adminAuditLog: `admin.auditlog`,
  adminLogs: "admin.logs",
  adminGrant: "admin.grant",
  adminRevoke: "admin.revoke",
  adminPreferencesGet: "admin.preferences.get",
  adminUserfsFolder: "admin.userfs.folder",
  adminUserfsFile: "admin.userfs.file",
  adminUserfsDirect: "admin.userfs.direct",
  adminUserfsTree: "admin.userfs.tree",
  adminUserfsQuota: "admin.userfs.quota",
  adminPreferencesPut: "admin.preferences.put",
  adminUsersList: "admin.users.list",
  adminUsersDelete: "admin.users.delete",
  adminUsersChangePswd: "admin.users.changepswd",
  adminUsersChangeEmail: "admin.users.changeemail",
  adminUsersApprove: "admin.users.approve",
  adminUsersDisapprove: "admin.users.disapprove",
  adminStats: "admin.stats",
  adminTokensGet: "admin.tokens.get",
  adminTokensPurgeAllDelete: "admin.tokens.purge.all",
  adminTokensPurgeUserDelete: "admin.tokens.purge.user",
  adminTokensPurgeOneDelete: "admin.tokens.purge.one",
  adminScopesPut: "admin.scopes.put",
  adminScopesGet: "admin.scopes.get",
  adminScopesAvailable: "admin.scopes.available",
  adminBugHuntList: "admin.bughunt.reports.list",
  adminBugHuntClose: "admin.bughunt.close",
  adminBugHuntOpen: "admin.bughunt.open",
  adminBugHuntGet: "admin.bughunt.get",
  adminBugHuntDelete: "admin.bughunt.delete",
  adminBugHuntStats: "admin.bughunt.stats",
  adminActivitiesList: "admin.activities.list",
  adminActivitiesUserGet: "admin.activities.user",
  adminActivitiesDelete: "admin.activities.delete",
  adminActivitiesDeleteUser: "admin.activities.delete.user",
  adminTotpGet: "admin.totp.get",
  adminTotpGetUser: "admin.totp.get.user",
  adminTotpDeactivateUser: "admin.totp.deactivate.user",
  adminTotpDeleteUser: "admin.totp.delete.user",
  adminAccessorsGet: "admin.accessors.get",
  adminAccessorsGetUser: "admin.accessors.get.user",
  adminAccessorsDelete: "admin.accessors.delete",
  adminAccessorsDeleteUser: "admin.accessors.delete.user",
  adminIndexGet: "admin.index.get",
  adminIndexGetUser: "admin.index.get.user",
  adminIndexUser: "admin.index.user",
  adminIndexDeleteUser: "admin.index.delete.user",
  adminShareInteract: "admin.share.interact",
  adminShareList: "admin.share.list",
  adminShareListUser: "admin.share.list.user",
  adminShareDelete: "admin.share.delete",
  adminShareMembersGet: "admin.share.members",
  adminShareKick: "admin.share.kick",
  adminShareAddUser: "admin.share.add.user",
  adminShareAccessorsGet: "admin.share.accessors.get",
  adminShareAccessorsDelete: "admin.share.accessors.delete",
  adminShareChangePswd: "admin.share.changepswd",
  adminShareRename: "admin.share.rename",
  adminShareChown: "admin.share.chown",
  adminShareQuotaGet: "admin.share.quota.get",
  adminShareQuotaPut: "admin.share.quota.put",
};

export const AdminScopeCaptions: Record<string, string> = {
  adminGod: "do everything",
  adminAuditLog: `view the audit log`,
  adminLogs: "view server logs",
  adminGrant: "grant admin",
  adminRevoke: "revoke admin",
  adminPreferencesGet: "get a user's preferences",
  adminUserfsFolder: "list the contents of a user's folder",
  adminUserfsFile: "read the contents of a user's file",
  adminUserfsDirect: "use Direct File Access on a user's filesystem",
  adminUserfsTree: "tree a user's filesystem",
  adminUserfsQuota: "retrieve a user's filesystem quota",
  adminPreferencesPut: "update a user's preferences",
  adminUsersList: "list users",
  adminUsersDelete: "delete a user",
  adminUsersChangePswd: "change a user's password",
  adminUsersChangeEmail: "change a user's email",
  adminUsersApprove: "approve a user",
  adminUsersDisapprove: "disapprove a user",
  adminStats: "view server statistics",
  adminTokensGet: "get all tokens",
  adminTokensPurgeAllDelete: "delete all tokens",
  adminTokensPurgeUserDelete: "delete a user's tokens",
  adminTokensPurgeOneDelete: "delete one token",
  adminScopesPut: "update an admin's scopes",
  adminScopesGet: "get an admin's scopes",
  adminScopesAvailable: "view available scopes",
  adminBugHuntList: "list bug reports",
  adminBugHuntClose: "close a bug report",
  adminBugHuntOpen: "reopen a bug report",
  adminBugHuntGet: "get a bug report",
  adminBugHuntDelete: "delete a bug report",
  adminBugHuntStats: "view BugHunt statistics",
  adminActivitiesList: "view all login activity",
  adminActivitiesUserGet: "view a user's login activity",
  adminActivitiesDelete: "delete all login activity",
  adminActivitiesDeleteUser: "delete a user's login activity",
  adminTotpGet: "get all TOTP nodes",
  adminTotpGetUser: "get TOTP info of a user",
  adminTotpDeactivateUser: "deactivate a user's TOTP",
  adminTotpDeleteUser: "delete a user's TOTP",
  adminAccessorsGet: "get all DFAs",
  adminAccessorsGetUser: "get a user's DFAs",
  adminAccessorsDelete: "delete all DFAs",
  adminAccessorsDeleteUser: "delete a user's DFAs",
  adminIndexGet: "get all filesystem indexes",
  adminIndexGetUser: "get a user's filesystem indexes",
  adminIndexUser: "force indexing for a user",
  adminIndexDeleteUser: "delete all indexes of a user",
  adminShareInteract: "interact with a user's share",
  adminShareList: "list all shares",
  adminShareListUser: "list a user's shares",
  adminShareDelete: "delete a share",
  adminShareMembersGet: "view a share's members",
  adminShareKick: "kick a user from a share",
  adminShareAddUser: "add a user to a share",
  adminShareAccessorsGet: "get all SDFAs",
  adminShareAccessorsDelete: "delete a share's SDFAs",
  adminShareChangePswd: "change a share's password",
  adminShareRename: "rename a share",
  adminShareChown: "change the owner of a share",
  adminShareQuotaGet: "get a share's quota",
  adminShareQuotaPut: "change a share's quota",
};
