import type { UserInfo, UserPreferences } from "$types/user";
import type { ReadableStore } from "$types/writable";
import type { IAccountUserContext } from "./contexts/account";
import type { ILoginActivityUserContext } from "./contexts/activity";
import type { IAppRegistrationUserContext } from "./contexts/appreg";
import type { IApplicationsUserContext } from "./contexts/apps";
import type { IChecksUserContext } from "./contexts/checks";
import type { IElevationUserContext } from "./contexts/elevation";
import type { IFilesystemUserContext } from "./contexts/files";
import type { IHelpersUserContext } from "./contexts/helpers";
import type { IIconsUserContext } from "./contexts/icons";
import type { IInitUserContext } from "./contexts/init";
import type { INotificationsUserContext } from "./contexts/notifications";
import type { IPowerUserContext } from "./contexts/power";
import type { IPreferencesUserContext } from "./contexts/preferences";
import type { IAppRendererUserContext } from "./contexts/renderer";
import type { IShortcutsUserContext } from "./contexts/shortcuts";
import type { ISpawnUserContext } from "./contexts/spawn";
import type { IThemesUserContext } from "./contexts/themes";
import type { IVersionUserContext } from "./contexts/version";
import type { IWallpaperUserContext } from "./contexts/wallpaper";
import type { IWorkspaceUserContext } from "./contexts/workspaces";
import type { IProcess } from "./process";
import type { IApplicationStorage, IFileAssocService, IGlobalDispatch, ILibraryManagement, IServiceHost } from "./service";
import type { IShellRuntime } from "./shell";

export interface IUserDaemon extends IProcess {
  username: string;
  token: string;
  userInfo: UserInfo;
  autoLoadComplete: boolean;
  safeMode: boolean;
  initialized: boolean;
  _blockLeaveInvocations: boolean;
  _toLoginInvoked: boolean;
  _criticalProcess: boolean;
  copyList: ReadableStore<string[]>;
  cutList: ReadableStore<string[]>;
  globalDispatch?: IGlobalDispatch;
  assoc?: IFileAssocService;
  serviceHost?: IServiceHost;
  libraries?: ILibraryManagement;
  account?: IAccountUserContext;
  activity?: ILoginActivityUserContext;
  apps?: IApplicationsUserContext;
  appreg?: IAppRegistrationUserContext;
  renderer?: IAppRendererUserContext;
  checks?: IChecksUserContext;
  elevation?: IElevationUserContext;
  files?: IFilesystemUserContext;
  helpers?: IHelpersUserContext;
  icons?: IIconsUserContext;
  init?: IInitUserContext;
  notifications?: INotificationsUserContext;
  power?: IPowerUserContext;
  preferencesCtx?: IPreferencesUserContext;
  spawn?: ISpawnUserContext;
  themes?: IThemesUserContext;
  version?: IVersionUserContext;
  wallpaper?: IWallpaperUserContext;
  workspaces?: IWorkspaceUserContext;
  shortcuts?: IShortcutsUserContext;
  get preferences(): ReadableStore<UserPreferences>;
  start(): Promise<false | undefined>;
  stop(): Promise<false | undefined>;
  startUserContexts(): Promise<void>;
  stopUserContexts(): Promise<void>;
  activateAdminBootstrapper(): Promise<void>;
  activateGlobalDispatch(): Promise<void>;
  appStorage(): IApplicationStorage | undefined;
  getShell(): IShellRuntime | undefined;
  updateGlobalDispatch(): void;
  getShell(): IShellRuntime | undefined;
}

export interface IUserContext {
  __init(): Promise<void>;
  _init(): Promise<void>;
  __deactivate(): Promise<void>;
  _deactivate(): Promise<void>;
}
