import type { UserInfo, UserPreferences } from "$types/user";
import type { ReadableStore } from "$types/writable";
import type { IAccountUserContext } from "./contexts/IAccountUserContext";
import type { IApplicationsUserContext } from "./contexts/IApplicationsUserContext";
import type { IAppRegistrationUserContext } from "./contexts/IAppRegistrationUserContext";
import type { IAppRendererUserContext } from "./contexts/IAppRendererUserContext";
import type { IChecksUserContext } from "./contexts/IChecksUserContext";
import type { IElevationUserContext } from "./contexts/IElevationUserContext";
import type { IFilesystemUserContext } from "./contexts/IFilesystemUserContext";
import type { IHelpersUserContext } from "./contexts/IHelpersUserContext";
import type { IIconsUserContext } from "./contexts/IIconsUserContext";
import type { IInitUserContext } from "./contexts/IInitUserContext";
import type { ILoginActivityUserContext } from "./contexts/ILoginActivityUserContext";
import type { INotificationsUserContext } from "./contexts/INotificationsUserContext";
import type { IPowerUserContext } from "./contexts/IPowerUserContext";
import type { IPreferencesUserContext } from "./contexts/IPreferencesUserContext";
import type { IShortcutsUserContext } from "./contexts/IShortcutsUserContext";
import type { ISpawnUserContext } from "./contexts/ISpawnUserContext";
import type { IThemesUserContext } from "./contexts/IThemesUserContext";
import type { IVersionUserContext } from "./contexts/IVersionUserContext";
import type { IWallpaperUserContext } from "./contexts/IWallpaperUserContext";
import type { IWorkspaceUserContext } from "./contexts/IWorkspaceUserContext";
import type { IProcess } from "./IProcess";
import type { IServiceHost } from "./IServiceHost";
import type { IServerConnector } from "./modules/IServerManager";
import type { IShellRuntime } from "./runtimes/IShellRuntime";
import type { IApplicationStorage } from "./services/IApplicationStorage";
import type { IFileAssocService } from "./services/IFileAssocService";
import type { IGlobalDispatch } from "./services/IGlobalDispatch";
import type { ILibraryManagement } from "./services/ILibraryManagement";

export interface IUserDaemon extends IProcess {
  username: string;
  token: string;
  userInfo: UserInfo;
  autoLoadComplete: boolean;
  safeMode: boolean;
  initialized: boolean;
  _blockLeaveInvocations: boolean;
  _toLoginInvoked: boolean;
  _criticalProcess: boolean;
  copyList: ReadableStore<string[]>;
  cutList: ReadableStore<string[]>;
  get globalDispatch(): IGlobalDispatch | undefined;
  get assoc(): IFileAssocService | undefined;
  serviceHost?: IServiceHost;
  get libraries(): ILibraryManagement | undefined;
  account?: IAccountUserContext;
  activity?: ILoginActivityUserContext;
  apps?: IApplicationsUserContext;
  appreg?: IAppRegistrationUserContext;
  renderer?: IAppRendererUserContext;
  checks?: IChecksUserContext;
  elevation?: IElevationUserContext;
  files?: IFilesystemUserContext;
  helpers?: IHelpersUserContext;
  icons?: IIconsUserContext;
  init?: IInitUserContext;
  notifications?: INotificationsUserContext;
  power?: IPowerUserContext;
  preferencesCtx?: IPreferencesUserContext;
  spawn?: ISpawnUserContext;
  themes?: IThemesUserContext;
  version?: IVersionUserContext;
  wallpaper?: IWallpaperUserContext;
  workspaces?: IWorkspaceUserContext;
  shortcuts?: IShortcutsUserContext;
  get preferences(): ReadableStore<UserPreferences>;
  start(): Promise<false | undefined>;
  stop(): Promise<false | undefined>;
  startUserContexts(): Promise<void>;
  stopUserContexts(): Promise<void>;
  appStorage(): IApplicationStorage | undefined;
  getShell(): IShellRuntime | undefined;
  updateGlobalDispatch(): void;
  getShell(): IShellRuntime | undefined;
  GetConnector<T extends IServerConnector>(name: string): T;
}

export interface IUserContext {
  __init(): Promise<void>;
  _init(): Promise<void>;
  __deactivate(): Promise<void>;
  _deactivate(): Promise<void>;
}
