import AdminPortalApp from "$apps/admin/adminportal/AdminPortal";
import type { AppKeyCombinations } from "$types/accelerator";
import type { AppStorage } from "$types/app";

export const BuiltinAppImportPaths: string[] = [
  "$apps/components/acceleratoroverview/AcceleratorOverview",
  "$apps/components/appinfo/AppInfo",
  "$apps/components/appinstaller/AppInstaller",
  "$apps/components/apppreinstall/AppPreinstall",
  "$apps/components/arcfind/ArcFind",
  "$apps/components/contextmenu/ContextMenu",
  "$apps/components/driveinfo/DriveInfo",
  "$apps/components/exit/Exit",
  "$apps/components/firstrun/FirstRun",
  "$apps/components/fsnewfile/FsNewFile",
  "$apps/components/fsnewfolder/FsNewFolder",
  "$apps/components/fsprogress/FsProgress",
  "$apps/components/fsprogressfail/FsProgressFail",
  "$apps/components/fsrenameitem/FsRenameItem",
  "$apps/components/globalloadindicator/GlobalLoadIndicator",
  "$apps/components/iconpicker/IconPicker",
  "$apps/components/iteminfo/ItemInfo",
  "$apps/components/messagebox/MessageBox",
  "$apps/components/messagecomposer/MessageComposer",
  "$apps/components/multiupdategui/MultiUpdateGui",
  "$apps/components/oopsnotifier/OopsNotifier",
  "$apps/components/oopsstacktracer/OopsStackTracer",
  "$apps/components/openwith/OpenWith",
  "$apps/components/securecontext/SecureContext",
  "$apps/components/shareconngui/ShareConnGui",
  "$apps/components/sharecreategui/ShareCreateGui",
  "$apps/components/sharelistgui/ShareListGui",
  "$apps/components/sharemgmtgui/ShareMgmtGui",
  "$apps/components/shell/Shell",
  "$apps/components/shellhost/ShellHost",
  "$apps/components/shortcutproperties/ShortcutProperties",
  "$apps/components/systemshortcuts/SystemShortcuts",
  "$apps/components/terminalwindow/TerminalWindow",
  "$apps/components/totpauthgui/TotpAuthGui",
  "$apps/components/totpsetupgui/TotpSetupGui",
  "$apps/components/trayhost/TrayHost",
  "$apps/components/updatenotifier/UpdateNotifier",
  "$apps/components/wallpaper/Wallpaper",
  "$apps/user/advsystemsettings/AdvSystemSettings",
  "$apps/user/appstore/AppStore",
  "$apps/user/arcterm/ArcTerm",
  "$apps/user/bughunt/BugHunt",
  "$apps/user/bughuntcreator/BugHuntCreator",
  "$apps/user/calculator/Calculator",
  "$apps/user/cod/Cod",
  "$apps/user/filemanager/fileManager",
  "$apps/user/hexedit/hexEdit",
  "$apps/user/imageviewer/imageViewer",
  "$apps/user/lightsoff/lightsOff",
  "$apps/user/logging/logging",
  "$apps/user/mediaplayer/mediaPlayer",
  "$apps/user/messages/messages",
  "$apps/user/pdfviewer/pdfViewer",
  "$apps/user/processes/processes",
  "$apps/user/qlorb/qlorb",
  "$apps/user/settings/systemSettings",
  "$apps/user/writer/writer",
];

export const AdminApps: AppStorage = [AdminPortalApp];

export const appShortcuts: [number, AppKeyCombinations][] = [];

export const AppOrigins: Record<string, string> = {
  builtin: "Built-in",
  userApps: "Third-party",
  injected: "Other",
  aefs: "Administrative",
};
