import type { AppKeyCombinations } from "$types/accelerator";

export const BuiltinAppImportPathAbsolutes = import.meta.glob([
  "$apps/components/acceleratoroverview/AcceleratorOverview",
  "$apps/components/appinfo/AppInfo",
  "$apps/components/appinstaller/AppInstaller",
  "$apps/components/apppreinstall/AppPreInstall",
  "$apps/components/arcfind/ArcFindProc",
  "$apps/components/contextmenu/contextMenu",
  "$apps/components/driveinfo/DriveInfo",
  "$apps/components/exit/ExitApp",
  "$apps/components/firstrun/FirstRun",
  "$apps/components/fsnewfile/FsNewFile",
  "$apps/components/fsnewfolder/FsNewFolder",
  "$apps/components/fsprogress/FsProgress",
  "$apps/components/fsprogressfail/FsProgressFail",
  "$apps/components/fsrenameitem/FsRenameItem",
  "$apps/components/iconpicker/IconPicker",
  "$apps/components/iteminfo/ItemInfo",
  "$apps/components/messagecomposer/MessageComposer",
  "$apps/components/multiupdategui/MultiUpdateGui",
  "$apps/components/oopsnotifier/OopsNotifier",
  "$apps/components/oopsstacktracer/OopsStackTracer",
  "$apps/components/openwith/OpenWith",
  "$apps/components/securecontext/SecureContext",
  "$apps/components/shareconngui/ShareConnGui",
  "$apps/components/sharecreategui/ShareCreateGui",
  "$apps/components/sharelistgui/ShareListGui",
  "$apps/components/sharemgmtgui/ShareMgmtGui",
  "$apps/components/shell/arcShell",
  "$apps/components/shellhost/shellHost",
  "$apps/components/shortcutproperties/ShortcutProperties",
  "$apps/components/systemshortcuts/SystemShortcutsProc",
  "$apps/components/totpauthgui/TotpAuthGui",
  "$apps/components/totpsetupgui/TotpSetupGui",
  "$apps/components/trayhost/TrayHostProc",
  "$apps/components/updatenotifier/UpdateNotifierApp",
  "$apps/components/wallpaper/wallpaper",
  "$apps/components/terminalwindow/TerminalWindow",
  "$apps/components/messagebox/messageBox",
  "$apps/components/globalloadindicator/GlobalLoadIndicator",
  "$apps/components/processinfo/ProcessInfoApp",
  "$apps/components/serviceinfo/ServiceInfo",
  "$apps/components/iconeditdialog/IconEditDialog",
  "$apps/components/arctermcolors/ArcTermColors",
  "$apps/user/advsystemsettings/AdvSystemSettings",
  "$apps/user/appstore/AppStore",
  "$apps/user/arcterm/ArcTerm",
  "$apps/user/bughunt/BugHunt",
  "$apps/user/bughuntcreator/BugHuntCreator",
  "$apps/user/calculator/calculator",
  "$apps/user/cod/cod",
  "$apps/user/filemanager/fileManager",
  "$apps/user/imageviewer/ImageViewer",
  "$apps/user/lightsoff/LightsOff",
  "$apps/user/logging/logging",
  "$apps/user/mediaplayer/MediaPlayer",
  "$apps/user/messages/Messages",
  "$apps/user/pdfviewer/PdfViewer",
  "$apps/user/processes/processManager",
  "$apps/user/qlorb/QlorbApp",
  "$apps/user/settings/systemSettings",
  "$apps/user/writer/writer",
  "$apps/user/iconeditor/IconEditorApp",
  "$apps/user/donut/DonutApp",
  "$apps/user/sqeleton/Sqeleton",
]);

export const AdminAppImportPathAbsolutes = import.meta.glob([
  "$apps/admin/adminportal/AdminPortal",
  "$apps/admin/executequery/ExecuteQueryApp",
])

export const appShortcuts: [number, AppKeyCombinations][] = [];
export const AppOrigins: Record<string, string> = {
  builtin: "Built-in",
  userApps: "Third-party",
  injected: "Other",
  aefs: "Administrative",
};
